package proxy

import (
	"context"
	"net/http"
	"strings"
	"sync/atomic"
	"time"

	"github.com/manaflow-ai/subrouter/internal/buildversion"
)

// TrafficStats counts client request outcomes for this worker process.
//
// It exists for the post-upgrade bake gate in deploy/macos/subrouter-guard.sh:
// a release that answers /_subrouter/health but breaks routing passes every
// readiness check, and only the outcome rates of real traffic show it. The
// counters are process-local and never reset, so a reader derives rates as
// count / (now - started_at) and compares one generation with the next.
//
// Only counts are kept. No account, token, path, or body is recorded.
type TrafficStats struct {
	startedUnix atomic.Int64

	requests    atomic.Uint64
	responses2x atomic.Uint64
	responses4x atomic.Uint64
	responses5x atomic.Uint64
	responseOth atomic.Uint64
	proxy5xx    atomic.Uint64
	upstream5xx atomic.Uint64
}

// NewTrafficStats returns counters whose rate window starts at now.
func NewTrafficStats(now time.Time) *TrafficStats {
	stats := &TrafficStats{}
	stats.startedUnix.Store(now.Unix())
	return stats
}

// TrafficSnapshot is the /_subrouter/traffic payload.
type TrafficSnapshot struct {
	StartedAt     string            `json:"started_at,omitempty"`
	UptimeSeconds int64             `json:"uptime_seconds"`
	Version       string            `json:"version"`
	Requests      uint64            `json:"requests"`
	Responses     TrafficByClass    `json:"responses"`
	Proxy5xx      uint64            `json:"proxy_5xx"`
	Upstream5xx   uint64            `json:"upstream_5xx"`
	Streams       StreamDropSummary `json:"stream_drops"`
}

// TrafficByClass groups completed responses by status class.
type TrafficByClass struct {
	Class2xx uint64 `json:"2xx"`
	Class4xx uint64 `json:"4xx"`
	Class5xx uint64 `json:"5xx"`
	Other    uint64 `json:"other"`
}

// StreamDropSummary repeats the stream drop counts that matter for a bake.
type StreamDropSummary struct {
	Proxy uint64 `json:"proxy"`
	Total uint64 `json:"total"`
}

// Snapshot reads the counters. drops may be nil.
func (t *TrafficStats) Snapshot(drops *StreamDropStats, now time.Time) TrafficSnapshot {
	snapshot := TrafficSnapshot{Version: buildversion.Version()}
	streams := drops.Snapshot()
	snapshot.Streams = StreamDropSummary{Proxy: streams.Proxy, Total: streams.Total}
	if t == nil {
		return snapshot
	}
	if started := t.startedUnix.Load(); started != 0 {
		snapshot.StartedAt = time.Unix(started, 0).UTC().Format(time.RFC3339)
		if uptime := now.Unix() - started; uptime > 0 {
			snapshot.UptimeSeconds = uptime
		}
	}
	snapshot.Requests = t.requests.Load()
	snapshot.Responses = TrafficByClass{
		Class2xx: t.responses2x.Load(),
		Class4xx: t.responses4x.Load(),
		Class5xx: t.responses5x.Load(),
		Other:    t.responseOth.Load(),
	}
	snapshot.Proxy5xx = t.proxy5xx.Load()
	snapshot.Upstream5xx = t.upstream5xx.Load()
	return snapshot
}

func (t *TrafficStats) observe(status int, upstream bool) {
	switch {
	case status >= 200 && status < 300:
		t.responses2x.Add(1)
	case status >= 400 && status < 500:
		t.responses4x.Add(1)
	case status >= 500 && status < 600:
		t.responses5x.Add(1)
		if upstream {
			t.upstream5xx.Add(1)
		} else {
			t.proxy5xx.Add(1)
		}
	default:
		t.responseOth.Add(1)
	}
}

type trafficRecordKey struct{}

// trafficRecord is the per-request state the counting middleware shares with
// the handlers below it through the request context.
type trafficRecord struct {
	// upstream is true when the status being written was passed through from
	// an upstream response rather than generated by subrouter itself.
	upstream atomic.Bool
}

// markUpstreamResponse records that the response about to be written carries
// the upstream's status. Every path that copies an upstream status to the
// client calls it; any 5xx written without it counts as proxy-generated.
func markUpstreamResponse(ctx context.Context, upstream bool) {
	if record, ok := ctx.Value(trafficRecordKey{}).(*trafficRecord); ok {
		record.upstream.Store(upstream)
	}
}

// trafficCounted wraps next so each non-control request is counted once.
func (t *TrafficStats) trafficCounted(next http.Handler) http.Handler {
	if t == nil {
		return next
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.HasPrefix(r.URL.Path, "/_subrouter/") || r.URL.Path == "/_subrouter" {
			next.ServeHTTP(w, r)
			return
		}
		if _, counted := r.Context().Value(trafficRecordKey{}).(*trafficRecord); counted {
			next.ServeHTTP(w, r)
			return
		}
		record := &trafficRecord{}
		t.requests.Add(1)
		writer := &trafficResponseWriter{ResponseWriter: w}
		defer func() {
			recovered := recover()
			status := writer.status
			if status == 0 {
				if recovered != nil {
					status = http.StatusInternalServerError
				} else {
					// net/http sends 200 for a handler that wrote nothing.
					status = http.StatusOK
				}
			}
			t.observe(status, writer.upstream)
			if recovered != nil {
				panic(recovered)
			}
		}()
		writer.record = record
		next.ServeHTTP(writer, r.WithContext(context.WithValue(r.Context(), trafficRecordKey{}, record)))
	})
}

// trafficResponseWriter captures the first status written. It forwards Flush
// and exposes Unwrap so http.ResponseController (used by ReverseProxy for
// flushing and protocol upgrades) reaches the underlying writer.
type trafficResponseWriter struct {
	http.ResponseWriter
	record   *trafficRecord
	status   int
	upstream bool
}

func (w *trafficResponseWriter) WriteHeader(status int) {
	if w.status == 0 && (status >= 200 || status == http.StatusSwitchingProtocols) {
		w.status = status
		w.upstream = w.record != nil && w.record.upstream.Load()
	}
	w.ResponseWriter.WriteHeader(status)
}

func (w *trafficResponseWriter) Write(body []byte) (int, error) {
	if w.status == 0 {
		w.status = http.StatusOK
		w.upstream = w.record != nil && w.record.upstream.Load()
	}
	return w.ResponseWriter.Write(body)
}

func (w *trafficResponseWriter) Flush() {
	if w.status == 0 {
		w.status = http.StatusOK
	}
	_ = http.NewResponseController(w.ResponseWriter).Flush()
}

func (w *trafficResponseWriter) Unwrap() http.ResponseWriter { return w.ResponseWriter }

// handleTraffic reports request outcome counts for this worker process. Like
// /_subrouter/stream-stats it is unauthenticated and carries counts only.
func (s Server) handleTraffic(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, s.Traffic.Snapshot(s.StreamDrops, time.Now()))
}
