package main

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/manaflow-ai/subrouter/internal/accounts"
	"github.com/manaflow-ai/subrouter/internal/storepath"
)

// Codex 0.157+ runs interactive sessions on a shared background server
// (app-server daemon) that keeps MCP servers, plugins and config warm. Any
// -c override forces a cold embedded server instead, which is what the
// launcher's provider block used to do on every launch (~10s on a busy Mac).
//
// There is one daemon per CODEX_HOME, so sr codex gets its own home whose
// config.toml is the user's config plus the Subrouter provider. Everything
// else (sessions, auth, skills, plugins, rules, logs) is a symlink into the
// user's Codex home, so history and resume stay shared. Plain codex keeps
// its own daemon and provider.

const (
	codexSharedHomeDirName   = "codex-home"
	codexSharedDaemonDisable = "SUBROUTER_CODEX_SHARED_DAEMON"
	codexSharedHomeHeader    = "# Generated by sr codex from %s on every launch; edit that file instead.\n"
)

// codexSharedHomeOwnedEntries are never linked from the source home: the
// config is generated, the daemon control and state directories must be
// per-home, and the models cache belongs to the provider that filled it.
// packages is per-home because Codex's installer writes absolute paths
// under $CODEX_HOME into it: through a link, a daemon start here re-points
// the user's own installation at this home.
var codexSharedHomeOwnedEntries = map[string]bool{
	"config.toml":        true,
	"app-server-control": true,
	"app-server-daemon":  true,
	"models_cache.json":  true,
	"packages":           true,
}

// codexSharedHomeCarriedSections are tables Codex itself writes when the
// user trusts a project or hook inside sr codex. They are kept across
// regenerations so a trust decision is not asked for again.
var codexSharedHomeCarriedSections = []string{"[projects.", "[hooks.state."}

func codexSharedHomeDir() string {
	return filepath.Join(storepath.StateDir(), codexSharedHomeDirName)
}

func codexSourceHome() (string, error) {
	if home := strings.TrimSpace(os.Getenv("CODEX_HOME")); home != "" {
		return filepath.Abs(home)
	}
	userHome, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(userHome, ".codex"), nil
}

// codexSharedDaemonEligible reports whether a launch can run on the shared
// server. Anything that needs a per-launch provider setting, or that Codex
// itself runs embedded, keeps the -c provider block.
func codexSharedDaemonEligible(args []string, localTarget bool, userEmail, accountID string, persistCapacity bool, retryHeader string) bool {
	if strings.TrimSpace(os.Getenv(codexSharedDaemonDisable)) == "0" {
		return false
	}
	if localTarget || userEmail != "" || accountID != "" || persistCapacity || retryHeader != "" {
		return false
	}
	if codexModelArg(args) != "" {
		// The model header routes the websocket upgrade before the first
		// frame names the model; it can only be sent per launch.
		return false
	}
	switch codexSubcommand(args) {
	case "", "resume", "fork":
	default:
		return false
	}
	for _, arg := range args {
		if arg == "--" {
			break
		}
		name, _, _ := strings.Cut(arg, "=")
		switch name {
		case "-c", "--config", "--enable", "--disable", "-p", "--profile", "--search",
			"--strict-config", "--oss", "--local-provider", "--no-daemon", "--remote",
			"--remote-auth-token-env", "--dangerously-bypass-hook-trust":
			return false
		}
		if strings.HasPrefix(arg, "-c") && len(arg) > 2 && !strings.HasPrefix(arg, "--") {
			return false
		}
	}
	return true
}

// prepareCodexSharedHome brings target in line with source and writes the
// generated config. It is idempotent and cheap: one directory listing, a
// few lstat calls, and a config write only when the content changed.
func prepareCodexSharedHome(source, target, baseURL string, notify []string) error {
	if err := os.MkdirAll(target, 0o700); err != nil {
		return err
	}
	if err := syncCodexSharedHomeLinks(source, target); err != nil {
		return err
	}
	if err := ensureCodexSharedDaemonPackage(source, target); err != nil {
		return err
	}
	sourceBody, err := os.ReadFile(filepath.Join(source, "config.toml"))
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	configPath := filepath.Join(target, "config.toml")
	previous, err := os.ReadFile(configPath)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	next := codexSharedHomeConfig(string(sourceBody), string(previous), source, target, baseURL, notify)
	if next == string(previous) {
		return nil
	}
	tmp := configPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(next), 0o600); err != nil {
		return err
	}
	return os.Rename(tmp, configPath)
}

func syncCodexSharedHomeLinks(source, target string) error {
	entries, err := os.ReadDir(source)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	for _, entry := range entries {
		name := entry.Name()
		if codexSharedHomeOwnedEntries[name] || strings.HasPrefix(name, "config.toml.") || strings.HasPrefix(name, "..") {
			// An owned entry must be this home's own; drop a link an older
			// build left.
			link := filepath.Join(target, name)
			if info, err := os.Lstat(link); err == nil && info.Mode()&fs.ModeSymlink != 0 {
				if err := os.Remove(link); err != nil {
					return err
				}
			}
			continue
		}
		want := filepath.Join(source, name)
		link := filepath.Join(target, name)
		info, err := os.Lstat(link)
		switch {
		case errors.Is(err, fs.ErrNotExist):
			if err := os.Symlink(want, link); err != nil && !errors.Is(err, fs.ErrExist) {
				return err
			}
		case err != nil:
			return err
		case info.Mode()&fs.ModeSymlink != 0:
			if current, _ := os.Readlink(link); current != want {
				if err := os.Remove(link); err != nil {
					return err
				}
				if err := os.Symlink(want, link); err != nil {
					return err
				}
			}
		default:
			// Codex created a real entry here before the source had one; it
			// is this home's own state and stays.
		}
	}
	// Links into the source whose target is gone would make Codex fail on a
	// missing file instead of creating a fresh one.
	own, err := os.ReadDir(target)
	if err != nil {
		return err
	}
	prefix := filepath.Clean(source) + string(filepath.Separator)
	for _, entry := range own {
		link := filepath.Join(target, entry.Name())
		if entry.Type()&fs.ModeSymlink == 0 {
			continue
		}
		current, err := os.Readlink(link)
		if err != nil || !strings.HasPrefix(current, prefix) {
			continue
		}
		if _, err := os.Stat(current); errors.Is(err, fs.ErrNotExist) {
			_ = os.Remove(link)
		}
	}
	return nil
}

// ensureCodexSharedDaemonPackage points this home's daemon package at the
// release the user's Codex already installed, so the first start needs no
// download. A release Codex's own updater installed here is left alone.
func ensureCodexSharedDaemonPackage(source, target string) error {
	release, err := filepath.EvalSymlinks(filepath.Join(source, "packages", "app-server-daemon", "current"))
	if err != nil || !isRegularFile(filepath.Join(release, "bin", "codex")) {
		return nil // nothing to reuse; Codex installs its own package here
	}
	root := filepath.Join(target, "packages", "app-server-daemon")
	current := filepath.Join(root, "current")
	if isRegularFile(filepath.Join(current, "bin", "codex")) {
		return nil
	}
	if err := os.MkdirAll(root, 0o700); err != nil {
		return err
	}
	tmp := current + ".sr-tmp"
	_ = os.Remove(tmp)
	if err := os.Symlink(release, tmp); err != nil {
		return err
	}
	return os.Rename(tmp, current)
}

func isRegularFile(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular()
}

type tomlSection struct {
	header string // trimmed header line, empty for the top-level preamble
	lines  []string
}

// splitTomlSections is a line scan, not a TOML parser. A multi-line array
// or string value may contain a line starting with "[" only if it is
// indented, which is how Codex and people write them.
func splitTomlSections(body string) []tomlSection {
	sections := []tomlSection{{}}
	for _, line := range strings.SplitAfter(body, "\n") {
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "[") {
			sections = append(sections, tomlSection{header: strings.TrimSpace(line)})
		}
		sections[len(sections)-1].lines = append(sections[len(sections)-1].lines, line)
	}
	return sections
}

func isSubrouterProviderHeader(header string) bool {
	inner := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(header, "["), "]"))
	return inner == "model_providers.subrouter" || strings.HasPrefix(inner, "model_providers.subrouter.")
}

// dropTopLevelKeys removes assignments of the given keys from the preamble,
// including a multi-line array value.
func dropTopLevelKeys(lines []string, drop func(key string) bool) []string {
	out := make([]string, 0, len(lines))
	depth := 0
	for _, line := range lines {
		if depth > 0 {
			depth += strings.Count(line, "[") - strings.Count(line, "]")
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		key = strings.Trim(strings.TrimSpace(key), `"'`)
		if ok && !strings.HasPrefix(strings.TrimSpace(line), "#") && drop(key) {
			if open := strings.Count(value, "[") - strings.Count(value, "]"); open > 0 {
				depth = open
			}
			continue
		}
		out = append(out, line)
	}
	return out
}

func codexSharedHomeConfig(sourceBody, previousBody, sourceHome, targetHome, baseURL string, notify []string) string {
	sections := splitTomlSections(sourceBody)
	addNotify := len(notify) > 0 && !tomlTopLevelKeyPresent(sourceBody, "notify")
	preamble := dropTopLevelKeys(sections[0].lines, func(key string) bool {
		if key == "notify" {
			return addNotify
		}
		return key == "model_provider" || isSubrouterOwnedCodexConfig(key+"=x")
	})

	var out strings.Builder
	fmt.Fprintf(&out, codexSharedHomeHeader, filepath.Join(sourceHome, "config.toml"))
	out.WriteString("model_provider = \"subrouter\"\n")
	if addNotify {
		quoted := make([]string, len(notify))
		for i, part := range notify {
			quoted[i] = tomlBasicString(part)
		}
		out.WriteString("notify = [" + strings.Join(quoted, ", ") + "]\n")
	}
	for _, line := range preamble {
		out.WriteString(line)
	}
	ensureNewline(&out)

	// Hook trust is keyed by the hooks file path, which Codex sees through
	// this home's symlink.
	sourceKey := `"` + filepath.Clean(sourceHome) + string(filepath.Separator)
	targetKey := `"` + filepath.Clean(targetHome) + string(filepath.Separator)
	present := map[string]bool{}
	for _, section := range sections[1:] {
		if isSubrouterProviderHeader(section.header) {
			continue
		}
		lines := section.lines
		if strings.HasPrefix(section.header, "[hooks.state.") {
			lines = append([]string(nil), lines...)
			lines[0] = strings.Replace(lines[0], sourceKey, targetKey, 1)
		}
		present[strings.TrimSpace(lines[0])] = true
		for _, line := range lines {
			out.WriteString(line)
		}
		ensureNewline(&out)
	}
	for _, section := range splitTomlSections(previousBody)[1:] {
		if present[section.header] || !hasAnyPrefix(section.header, codexSharedHomeCarriedSections) {
			continue
		}
		present[section.header] = true
		for _, line := range section.lines {
			out.WriteString(line)
		}
		ensureNewline(&out)
	}

	out.WriteString("\n[model_providers.subrouter]\n")
	out.WriteString("name = \"Subrouter\"\n")
	out.WriteString("base_url = " + strconv.Quote(baseURL) + "\n")
	out.WriteString("experimental_bearer_token = \"subrouter\"\n")
	out.WriteString("wire_api = \"responses\"\n")
	out.WriteString("supports_websockets = true\n")
	out.WriteString("http_headers = " + codexSubrouterHeaders("", "", "") + "\n")
	return out.String()
}

func ensureNewline(out *strings.Builder) {
	if s := out.String(); s != "" && !strings.HasSuffix(s, "\n") {
		out.WriteByte('\n')
	}
}

func hasAnyPrefix(value string, prefixes []string) bool {
	for _, prefix := range prefixes {
		if strings.HasPrefix(value, prefix) {
			return true
		}
	}
	return false
}

func prepareCodexSharedHomeForLaunch(target, baseURL string) error {
	source, err := codexSourceHome()
	if err != nil {
		return err
	}
	return prepareCodexSharedHome(source, target, baseURL, codexSharedNotifyArgs(accounts.DefaultCodexStore().StoreDir()))
}

// codexSharedNotifyArgs is the notify hook for the shared home. It cannot
// name a launch, because one daemon serves every sr codex window; the hook
// matches the turn's cwd to a running shared launch instead.
func codexSharedNotifyArgs(storeDir string) []string {
	executable, err := sessionHookExecutable()
	if err != nil {
		return nil
	}
	return []string{executable, sessionNotifyCommand, "--shared", "--store-dir", storeDir}
}
