package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"time"

	"github.com/BurntSushi/toml"
	"github.com/manaflow-ai/subrouter/internal/accounts"
	"github.com/manaflow-ai/subrouter/internal/storepath"
)

// Codex 0.157+ runs interactive sessions on a shared background server
// (app-server daemon) that keeps MCP servers, plugins and config warm. Any
// -c override forces a cold embedded server instead, which is what the
// launcher's provider block used to do on every launch (~10s on a busy Mac).
//
// There is one daemon per CODEX_HOME, so sr codex gets its own home whose
// config.toml is the user's config plus the Subrouter provider. Everything
// else (sessions, auth, skills, plugins, rules, logs) is a symlink into the
// user's Codex home, so history and resume stay shared. Plain codex keeps
// its own daemon and provider.

const (
	codexSharedHomeDirName   = "codex-home"
	codexSharedDaemonDisable = "SUBROUTER_CODEX_SHARED_DAEMON"
	codexSharedHomeHeader    = "# Generated by sr codex from %s on every launch.\n# Settings Codex saves here are kept; edit that file for anything else.\n\n"

	// Private files of the shared home, never linked and never adopted.
	codexSharedBaseFile   = ".sr-config-base.toml" // the last generated config, the merge base
	codexSharedSourceFile = ".sr-source"           // the Codex home this one mirrors
	codexSharedLockFile   = ".sr-prepare.lock"
	codexSharedLockWait   = 10 * time.Second
	codexSharedStaleLock  = time.Minute
)

// codexSharedHomeOwnedEntries are never linked from the source home: the
// config is generated, the daemon control and state directories must be
// per-home, and the models cache belongs to the provider that filled it.
// packages is per-home because Codex's installer writes absolute paths
// under $CODEX_HOME into it: through a link, a daemon start here re-points
// the user's own installation at this home.
var codexSharedHomeOwnedEntries = map[string]bool{
	"config.toml":        true,
	"app-server-control": true,
	"app-server-daemon":  true,
	"models_cache.json":  true,
	"packages":           true,
}

// codexSharedHomeSourceDirs exist in the source before linking, so a
// first-ever sr codex launch does not give the shared home a private copy.
var codexSharedHomeSourceDirs = []string{"sessions", "archived_sessions", "memories", "shell_snapshots"}

// codexSharedOwnedKeys always come from the generated config: a merge must
// never let a saved value route sr codex away from Subrouter.
var codexSharedOwnedKeys = [][]string{
	{"model_provider"},
	{"model_providers", "subrouter"},
	{"allow_symlinked_codex_home"},
}

// codexSharedDaemonEligible reports whether a launch can run on the shared
// server. Anything that needs a per-launch provider setting, or that Codex
// itself runs embedded, keeps the -c provider block.
func codexSharedDaemonEligible(args []string, localTarget bool, userEmail, accountID string, persistCapacity bool, retryHeader string) bool {
	if strings.TrimSpace(os.Getenv(codexSharedDaemonDisable)) == "0" {
		return false
	}
	if localTarget || userEmail != "" || accountID != "" || persistCapacity || retryHeader != "" {
		return false
	}
	if strings.TrimSpace(os.Getenv("SUBROUTER_CODEX_BASE_URL")) != "" {
		// An arbitrary URL has no stable name to key a shared home by.
		return false
	}
	if codexModelArg(args) != "" {
		// The model header routes the websocket upgrade before the first
		// frame names the model; it can only be sent per launch.
		return false
	}
	switch codexSubcommand(args) {
	case "", "resume", "fork":
	default:
		return false
	}
	for _, arg := range args {
		if arg == "--" {
			break
		}
		name, _, _ := strings.Cut(arg, "=")
		switch name {
		case "-c", "--config", "--enable", "--disable", "-p", "--profile", "--search",
			"--strict-config", "--oss", "--local-provider", "--no-daemon", "--remote",
			"--remote-auth-token-env", "--dangerously-bypass-hook-trust", "-m", "--model":
			return false
		}
		// Attached short values: -cKEY=V, -pNAME, -mMODEL.
		if len(arg) > 2 && arg[0] == '-' && arg[1] != '-' && strings.ContainsRune("cpm", rune(arg[1])) {
			return false
		}
	}
	return true
}

func canonicalPath(path string) string {
	abs, err := filepath.Abs(path)
	if err != nil {
		return filepath.Clean(path)
	}
	if resolved, err := filepath.EvalSymlinks(abs); err == nil {
		return resolved
	}
	return abs
}

func defaultCodexHome() (string, error) {
	userHome, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(userHome, ".codex"), nil
}

// isCodexSharedHome reports whether dir is (or is inside) a shared home.
func isCodexSharedHome(dir string) bool {
	// The marker also works when the launching shell's state dir differs.
	if isRegularFile(filepath.Join(dir, codexSharedSourceFile)) {
		return true
	}
	state := canonicalPath(storepath.StateDir())
	rel, err := filepath.Rel(state, canonicalPath(dir))
	if err != nil || rel == "." || strings.HasPrefix(rel, "..") {
		return false
	}
	first := strings.Split(rel, string(filepath.Separator))[0]
	return first == codexSharedHomeDirName || strings.HasPrefix(first, codexSharedHomeDirName+"-")
}

// codexSourceHome is the user's Codex home. A shell that Codex spawned has
// CODEX_HOME set to the shared home; a nested sr codex from there must mirror
// the same source, never itself.
func codexSourceHome() (string, error) {
	home := strings.TrimSpace(os.Getenv("CODEX_HOME"))
	if home == "" {
		return defaultCodexHome()
	}
	if isCodexSharedHome(home) {
		if body, err := os.ReadFile(filepath.Join(home, codexSharedSourceFile)); err == nil {
			if recorded := strings.TrimSpace(string(body)); filepath.IsAbs(recorded) && !isCodexSharedHome(recorded) {
				return recorded, nil
			}
		}
		return defaultCodexHome()
	}
	return filepath.Abs(home)
}

// codexSharedHomeDir keys the shared home by source Codex home and by an
// explicitly selected server, so neither leaks into another's windows.
func codexSharedHomeDir(source string) string {
	name := codexSharedHomeDirName
	var key []string
	if def, err := defaultCodexHome(); err != nil || canonicalPath(source) != canonicalPath(def) {
		key = append(key, "home="+canonicalPath(source))
	}
	if server := explicitServerTarget(); server != "" {
		key = append(key, "server="+server)
	}
	if len(key) > 0 {
		sum := sha256.Sum256([]byte(strings.Join(key, "\n")))
		name += "-" + hex.EncodeToString(sum[:6])
	}
	return filepath.Join(storepath.StateDir(), name)
}

func prepareCodexSharedHomeForLaunch(baseURL string, recovery ...bool) (string, error) {
	source, err := codexSourceHome()
	if err != nil {
		return "", err
	}
	target := codexSharedHomeDir(source)
	notify := codexSharedNotifyArgs(accounts.DefaultCodexStore().StoreDir())
	return target, prepareCodexSharedHome(source, target, baseURL, notify, recovery...)
}

// prepareCodexSharedHome brings target in line with source and merges the
// generated config. Concurrent launches serialize on a lock file.
func prepareCodexSharedHome(source, target, baseURL string, notify []string, recovery ...bool) error {
	if canonicalPath(source) == canonicalPath(target) || isCodexSharedHome(source) {
		return fmt.Errorf("refusing to mirror the shared Codex home %s into itself", target)
	}
	if err := os.MkdirAll(target, 0o700); err != nil {
		return err
	}
	unlock, err := lockCodexSharedHome(target)
	if err != nil {
		return err
	}
	defer unlock()
	if err := writeFileAtomic(filepath.Join(target, codexSharedSourceFile), []byte(canonicalPath(source)+"\n"), 0o600); err != nil {
		return err
	}
	for _, dir := range codexSharedHomeSourceDirs {
		if err := os.MkdirAll(filepath.Join(source, dir), 0o700); err != nil {
			return err
		}
	}
	if err := syncCodexSharedHomeLinks(source, target); err != nil {
		return err
	}
	if err := ensureCodexSharedDaemonPackage(source, target); err != nil {
		return err
	}
	return mergeCodexSharedHomeConfig(source, target, baseURL, notify, recovery...)
}

func lockCodexSharedHome(target string) (func(), error) {
	lockPath := filepath.Join(target, codexSharedLockFile)
	deadline := time.Now().Add(codexSharedLockWait)
	for {
		file, err := os.OpenFile(lockPath, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
		if err == nil {
			_ = file.Close()
			return func() { _ = os.Remove(lockPath) }, nil
		}
		if info, statErr := os.Stat(lockPath); statErr == nil && time.Since(info.ModTime()) > codexSharedStaleLock {
			_ = os.Remove(lockPath)
			continue
		}
		if time.Now().After(deadline) {
			return nil, fmt.Errorf("another sr codex launch is preparing %s", target)
		}
		time.Sleep(20 * time.Millisecond)
	}
}

func isCodexSharedPrivate(name string) bool {
	return strings.HasPrefix(name, ".sr-") || strings.HasPrefix(name, ".config.toml.") || strings.HasPrefix(name, "."+codexSharedBaseFile)
}

func syncCodexSharedHomeLinks(source, target string) error {
	entries, err := os.ReadDir(source)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	inSource := map[string]bool{}
	for _, entry := range entries {
		name := entry.Name()
		inSource[name] = true
		link := filepath.Join(target, name)
		if codexSharedHomeOwnedEntries[name] || strings.HasPrefix(name, "config.toml.") || strings.HasPrefix(name, "..") || isCodexSharedPrivate(name) {
			// An owned entry must be this home's own; drop a link an older
			// build left.
			if info, err := os.Lstat(link); err == nil && info.Mode()&fs.ModeSymlink != 0 {
				if err := os.Remove(link); err != nil {
					return err
				}
			}
			continue
		}
		want := filepath.Join(source, name)
		info, err := os.Lstat(link)
		switch {
		case errors.Is(err, fs.ErrNotExist):
			if err := os.Symlink(want, link); err != nil && !errors.Is(err, fs.ErrExist) {
				return err
			}
		case err != nil:
			return err
		case info.Mode()&fs.ModeSymlink != 0:
			if current, _ := os.Readlink(link); current != want {
				if err := os.Remove(link); err != nil {
					return err
				}
				if err := os.Symlink(want, link); err != nil {
					return err
				}
			}
		default:
			// Both homes have a real entry; neither can be merged into the
			// other, so this home keeps its own.
		}
	}

	own, err := os.ReadDir(target)
	if err != nil {
		return err
	}
	// Directories Codex created here while the source had none move into the
	// source, so plain codex and sr codex keep one history. Files are never
	// moved: they may be Codex's atomic-write temporaries or live databases.
	// The rename refuses to replace anything plain codex created meanwhile.
	var adopt []string
	prefix := filepath.Clean(source) + string(filepath.Separator)
	for _, entry := range own {
		name := entry.Name()
		link := filepath.Join(target, name)
		if entry.Type()&fs.ModeSymlink != 0 {
			current, err := os.Readlink(link)
			if err == nil && strings.HasPrefix(current, prefix) {
				if _, err := os.Stat(current); errors.Is(err, fs.ErrNotExist) {
					_ = os.Remove(link) // a link to a deleted source entry
				}
			}
			continue
		}
		if !entry.IsDir() || strings.HasPrefix(name, ".") || inSource[name] || codexSharedHomeOwnedEntries[name] {
			continue
		}
		adopt = append(adopt, name)
	}
	for _, name := range adopt {
		from, to := filepath.Join(target, name), filepath.Join(source, name)
		if err := renameNoReplace(from, to); err != nil {
			continue // exists in the source, another filesystem, or unsupported
		}
		if err := os.Symlink(to, from); err != nil {
			return err
		}
	}
	return nil
}

// ensureCodexSharedDaemonPackage points this home's daemon package at the
// release the user's Codex has installed, following the user's upgrades. A
// release Codex's own updater installed here is left alone.
func ensureCodexSharedDaemonPackage(source, target string) error {
	release, err := filepath.EvalSymlinks(filepath.Join(source, "packages", "app-server-daemon", "current"))
	if err != nil || !isRegularFile(filepath.Join(release, "bin", "codex")) {
		return nil // nothing to reuse; Codex installs its own package here
	}
	root := filepath.Join(target, "packages", "app-server-daemon")
	current := filepath.Join(root, "current")
	if info, err := os.Lstat(current); err == nil {
		if info.Mode()&fs.ModeSymlink == 0 {
			return nil // a real install by Codex
		}
		if dest, _ := os.Readlink(current); dest == release {
			return nil
		}
	}
	if err := os.MkdirAll(root, 0o700); err != nil {
		return err
	}
	tmp := filepath.Join(root, fmt.Sprintf(".current-%d", os.Getpid()))
	_ = os.Remove(tmp)
	if err := os.Symlink(release, tmp); err != nil {
		return err
	}
	if err := os.Rename(tmp, current); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

func isRegularFile(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular()
}

func decodeTomlTable(body []byte) (map[string]any, error) {
	table := map[string]any{}
	if len(bytes.TrimSpace(body)) == 0 {
		return table, nil
	}
	if _, err := toml.Decode(string(body), &table); err != nil {
		return nil, err
	}
	return table, nil
}

func readTomlFile(path string) ([]byte, map[string]any, error) {
	body, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, map[string]any{}, nil
	}
	if err != nil {
		return nil, nil, err
	}
	table, err := decodeTomlTable(body)
	return body, table, err
}

// mergeCodexSharedHomeConfig is a three-way merge. The base is the config
// this home was last given; the current file is that plus what Codex saved
// inside sr codex (/model, notices, trust); the new generation is the user's
// config now. A setting only Codex changed keeps Codex's value; anything the
// user changed, including revoking trust, follows the user's config.
func mergeCodexSharedHomeConfig(source, target, baseURL string, notify []string, recovery ...bool) error {
	_, user, err := readTomlFile(filepath.Join(source, "config.toml"))
	if err != nil {
		return fmt.Errorf("read %s: %w", filepath.Join(source, "config.toml"), err)
	}
	generated := codexSharedGeneratedConfig(user, source, target, baseURL, notify, len(recovery) > 0 && recovery[0])
	_, base, err := readTomlFile(filepath.Join(target, codexSharedBaseFile))
	if err != nil {
		base = nil
	}
	currentPath := filepath.Join(target, "config.toml")
	currentBody, current, err := readTomlFile(currentPath)
	if err != nil {
		current = nil // unreadable: nothing Codex saved can be recovered
	}
	if base == nil || current == nil || !isRegularFile(filepath.Join(target, codexSharedBaseFile)) {
		base, current = generated, generated
	}
	merged := mergeTomlTables(base, current, generated)
	for _, path := range codexSharedOwnedKeys {
		setTomlPath(merged, path, getTomlPath(generated, path))
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, codexSharedHomeHeader, filepath.Join(source, "config.toml"))
	if err := toml.NewEncoder(&out).Encode(merged); err != nil {
		return err
	}
	var baseOut bytes.Buffer
	if err := toml.NewEncoder(&baseOut).Encode(generated); err != nil {
		return err
	}
	if !bytes.Equal(out.Bytes(), currentBody) {
		if err := writeFileAtomic(currentPath, out.Bytes(), 0o600); err != nil {
			return err
		}
	}
	return writeFileAtomic(filepath.Join(target, codexSharedBaseFile), baseOut.Bytes(), 0o600)
}

// codexSharedGeneratedConfig is the user's config routed through Subrouter.
func codexSharedGeneratedConfig(user map[string]any, source, target, baseURL string, notify []string, recovery bool) map[string]any {
	out := deepCopyToml(user).(map[string]any)
	out["model_provider"] = "subrouter"
	providers := mapOrNew(out["model_providers"])
	provider := map[string]any{
		"name":                      "Subrouter",
		"base_url":                  baseURL,
		"experimental_bearer_token": "subrouter",
		"wire_api":                  "responses",
		"supports_websockets":       true,
		"request_max_retries":       codexProviderRequestMaxRetries,
		"stream_max_retries":        codexProviderStreamMaxRetries,
		"http_headers": map[string]any{
			"X-Subrouter-Agent": "codex",
		},
	}
	if recovery {
		headers := provider["http_headers"].(map[string]any)
		headers["X-Subrouter-Capacity-Retry"] = "persist"
		headers["X-Subrouter-Capacity-Retryable"] = "1"
		provider["request_max_retries"] = 100
		provider["stream_max_retries"] = 100
		features := mapOrNew(out["features"])
		features["goals"] = true
		out["features"] = features
	}
	providers["subrouter"] = provider
	out["model_providers"] = providers
	// Codex's own sandbox refuses writable roots under a CODEX_HOME that has
	// symlinked components (memories, worktrees) unless this is set. It is
	// forced even over an explicit false: every link here points into the
	// user's own Codex home, and without it those features fail.
	out["allow_symlinked_codex_home"] = true
	if _, ok := out["notify"]; !ok && len(notify) > 0 {
		values := make([]any, len(notify))
		for i, part := range notify {
			values[i] = part
		}
		out["notify"] = values
	}
	// Hook trust is keyed by the hooks file path, which Codex sees under this
	// home. Codex canonicalizes CODEX_HOME, so match either spelling.
	if hooks, ok := out["hooks"].(map[string]any); ok {
		if state, ok := hooks["state"].(map[string]any); ok {
			rekeyed := map[string]any{}
			targetPrefix := canonicalPath(target) + string(filepath.Separator)
			for key, value := range state {
				newKey := key
				for _, prefix := range []string{filepath.Clean(source), canonicalPath(source)} {
					if rest, ok := strings.CutPrefix(key, prefix+string(filepath.Separator)); ok {
						newKey = targetPrefix + rest
						break
					}
				}
				rekeyed[newKey] = value
			}
			hooks["state"] = rekeyed
		}
	}
	return out
}

func mapOrNew(value any) map[string]any {
	if table, ok := value.(map[string]any); ok {
		return table
	}
	return map[string]any{}
}

func deepCopyToml(value any) any {
	switch v := value.(type) {
	case map[string]any:
		out := make(map[string]any, len(v))
		for key, item := range v {
			out[key] = deepCopyToml(item)
		}
		return out
	case []any:
		out := make([]any, len(v))
		for i, item := range v {
			out[i] = deepCopyToml(item)
		}
		return out
	case []map[string]any:
		out := make([]map[string]any, len(v))
		for i, item := range v {
			out[i] = deepCopyToml(item).(map[string]any)
		}
		return out
	default:
		return v
	}
}

// mergeTomlTables merges tables key by key and treats every non-table value,
// arrays included, as one value. On a conflict the user's config wins.
func mergeTomlTables(base, current, generated map[string]any) map[string]any {
	out := map[string]any{}
	keys := map[string]bool{}
	for _, table := range []map[string]any{base, current, generated} {
		for key := range table {
			keys[key] = true
		}
	}
	for key := range keys {
		b, inBase := base[key]
		c, inCurrent := current[key]
		g, inGenerated := generated[key]
		bt, bIsTable := b.(map[string]any)
		ct, cIsTable := c.(map[string]any)
		gt, gIsTable := g.(map[string]any)
		allTables := (cIsTable || !inCurrent) && (gIsTable || !inGenerated) && (bIsTable || !inBase)
		if allTables && (inCurrent || inGenerated) {
			// A table removed on one side and edited on the other stays;
			// removed on one side and untouched on the other goes.
			if inCurrent && inGenerated || !reflect.DeepEqual(orEmpty(bt), orEmpty(ct)) && inCurrent || !reflect.DeepEqual(orEmpty(bt), orEmpty(gt)) && inGenerated {
				out[key] = mergeTomlTables(orEmpty(bt), orEmpty(ct), orEmpty(gt))
			}
			continue
		}
		currentUnchanged := inCurrent == inBase && (!inCurrent || reflect.DeepEqual(c, b))
		generatedUnchanged := inGenerated == inBase && (!inGenerated || reflect.DeepEqual(g, b))
		switch {
		case currentUnchanged:
			if inGenerated {
				out[key] = deepCopyToml(g)
			}
		case generatedUnchanged:
			if inCurrent {
				out[key] = deepCopyToml(c)
			}
		default:
			if inGenerated {
				out[key] = deepCopyToml(g)
			}
		}
	}
	return out
}

func orEmpty(table map[string]any) map[string]any {
	if table == nil {
		return map[string]any{}
	}
	return table
}

func getTomlPath(table map[string]any, path []string) any {
	var value any = table
	for _, key := range path {
		next, ok := value.(map[string]any)
		if !ok {
			return nil
		}
		value = next[key]
	}
	return value
}

func setTomlPath(table map[string]any, path []string, value any) {
	for _, key := range path[:len(path)-1] {
		next, ok := table[key].(map[string]any)
		if !ok {
			next = map[string]any{}
			table[key] = next
		}
		table = next
	}
	last := path[len(path)-1]
	if value == nil {
		delete(table, last)
		return
	}
	table[last] = deepCopyToml(value)
}

// codexSharedNotifyArgs is the notify hook for the shared home. It cannot
// name a launch, because one daemon serves every sr codex window; the hook
// matches the turn's thread or working directory to a running shared launch.
func codexSharedNotifyArgs(storeDir string) []string {
	executable, err := sessionHookExecutable()
	if err != nil {
		return nil
	}
	return []string{executable, sessionNotifyCommand, "--shared", "--store-dir", storeDir}
}

// codexCdArg is the working directory a launch asks Codex to use.
func codexCdArg(args []string) string {
	dir := ""
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		switch {
		case (arg == "-C" || arg == "--cd") && i+1 < len(args):
			dir = args[i+1]
			i++
		case strings.HasPrefix(arg, "--cd="):
			dir = strings.TrimPrefix(arg, "--cd=")
		case strings.HasPrefix(arg, "-C") && len(arg) > 2:
			dir = strings.TrimPrefix(strings.TrimPrefix(arg, "-C"), "=")
		}
	}
	if dir == "" {
		return ""
	}
	abs, err := filepath.Abs(dir)
	if err != nil {
		return ""
	}
	return abs
}
